import 'package:flutter/material.dart';
import '../../core/authorization/permission_keys.dart';
import 'route_names.dart';

/// NavigationItem: কেন্দ্রীভূত নেভিগেশন আইটেম ডেটা মডেল
class NavigationItem {
  final String id;
  final String title;
  final String? englishTitle;
  final IconData icon;
  final String route;
  final List<NavigationItem> children;
  final String? permissionKey;
  final List<String>? requiredAnyPermissions;
  final List<String>? requiredAllPermissions;
  final bool isVisible;
  final int sortOrder;
  final String? badgeText;
  final String? description;
  final bool isStandalone;

  const NavigationItem({
    required this.id,
    required this.title,
    this.englishTitle,
    required this.icon,
    required this.route,
    this.children = const [],
    this.permissionKey,
    this.requiredAnyPermissions,
    this.requiredAllPermissions,
    this.isVisible = true,
    required this.sortOrder,
    this.badgeText,
    this.description,
    this.isStandalone = false,
  });

  bool get hasChildren => children.isNotEmpty;
}

/// BreadcrumbItem: ব্রেডক্রাম্ব প্রদর্শনের জন্য সহায়ক মডেল
class BreadcrumbItem {
  final String title;
  final String route;
  final bool isCurrent;

  const BreadcrumbItem({
    required this.title,
    required this.route,
    this.isCurrent = false,
  });
}

/// NavigationRegistry: সেন্ট্রালাইজড নেভিগেশন ও সাব-সাইডবার রেজিস্ট্রি
///
/// তিজারাহ সমিতি সফটওয়্যারের সকল মডিউল, সাব-মডিউল ও রুট কনফিগারেশন
/// এই রেজিস্ট্রি থেকে পরিচালিত হয়।
class NavigationRegistry {
  NavigationRegistry._();

  /// ১৩টি প্রধান প্যারেন্ট মডিউল তালিকা
  static const List<NavigationItem> mainModules = [
    // ১. ড্যাশবোর্ড (Standalone)
    NavigationItem(
      id: 'dashboard',
      title: 'ড্যাশবোর্ড',
      englishTitle: 'Dashboard',
      icon: Icons.dashboard_outlined,
      route: RouteNames.dashboard,
      sortOrder: 1,
      isStandalone: true,
      description: 'সার্বিক সারাংশ ও নিয়ন্ত্রণ কেন্দ্র',
      children: [],
    ),

    // ২. সংগঠন, ব্যবহারকারী ও নিরাপত্তা
    NavigationItem(
      id: 'organization_security',
      title: 'সংগঠন, ব্যবহারকারী ও নিরাপত্তা',
      englishTitle: 'Organization & Security',
      icon: Icons.security_outlined,
      route: RouteNames.orgSecurity,
      sortOrder: 2,
      description: 'সমিতির পরিচিতি, সদস্য ইউজার ও নিরাপত্তা ব্যবস্থাপনা',
      children: [
        NavigationItem(
          id: 'org_info',
          title: 'সংগঠনের তথ্য',
          englishTitle: 'Organization Profile',
          icon: Icons.apartment_outlined,
          route: RouteNames.orgInfo,
          sortOrder: 1,
          description: 'সমিতির মৌলিক তথ্য, রেজি. নম্বর ও যোগাযোগের ঠিকানা',
        ),
        NavigationItem(
          id: 'org_users',
          title: 'ব্যবহারকারী',
          englishTitle: 'User Accounts',
          icon: Icons.people_outline,
          route: RouteNames.orgUsers,
          sortOrder: 2,
          description: 'অপারেটর, অ্যাডমিন ও সংগ্রাহক ইউজার তালিকা',
          permissionKey: PermissionKeys.userView,
        ),
        NavigationItem(
          id: 'org_roles',
          title: 'ভূমিকা ও অনুমতি',
          englishTitle: 'Roles & Permissions',
          icon: Icons.admin_panel_settings_outlined,
          route: RouteNames.orgRoles,
          sortOrder: 3,
          description: 'রোলভিত্তিক অ্যাক্সেস ও পারমিশন ম্যাট্রিক্স',
          permissionKey: PermissionKeys.roleView,
        ),
        NavigationItem(
          id: 'org_login_sec',
          title: 'লগইন ও নিরাপত্তা',
          englishTitle: 'Login Security',
          icon: Icons.lock_outline,
          route: RouteNames.orgLoginSecurity,
          sortOrder: 4,
          description: 'টু-ফ্যাক্টর, পাসওয়ার্ড নীতি ও নিরাপত্তা কনফিগ',
        ),
        NavigationItem(
          id: 'org_sessions',
          title: 'সেশন ও ডিভাইস',
          englishTitle: 'Sessions & Devices',
          icon: Icons.devices_outlined,
          route: RouteNames.orgSessions,
          sortOrder: 5,
          description: 'সক্রিয় লগইন সেশন ও ডিভাইস নিয়ন্ত্রণ',
          permissionKey: PermissionKeys.sessionView,
        ),
        NavigationItem(
          id: 'org_logs',
          title: 'নিরাপত্তা লগ',
          englishTitle: 'Security Logs',
          icon: Icons.history_edu_outlined,
          route: RouteNames.orgLogs,
          sortOrder: 6,
          description: 'লগইন হিস্টোরি ও নিরাপত্তা অডিট ট্রেইল',
          permissionKey: PermissionKeys.auditLogView,
        ),
      ],
    ),

    // ৩. সদস্য ব্যবস্থাপনা
    NavigationItem(
      id: 'members',
      title: 'সদস্য ব্যবস্থাপনা',
      englishTitle: 'Member Management',
      icon: Icons.group_outlined,
      route: RouteNames.members,
      sortOrder: 3,
      description: 'সমিতির সম্মানিত সদস্যদের ডাটাবেজ ও হিসাব বিবরণী',
      children: [
        NavigationItem(
          id: 'members_list',
          title: 'সদস্য তালিকা',
          englishTitle: 'Member Directory',
          icon: Icons.badge_outlined,
          route: RouteNames.memberList,
          sortOrder: 1,
          description: 'সকল সক্রিয় ও স্থগিত সদস্যদের তালিকা',
        ),
        NavigationItem(
          id: 'members_new',
          title: 'নতুন সদস্য',
          englishTitle: 'New Member Onboarding',
          icon: Icons.person_add_alt_outlined,
          route: RouteNames.memberNew,
          sortOrder: 2,
          description: 'নতুন সদস্য অন্তর্ভুক্তি ফরম',
        ),
        NavigationItem(
          id: 'members_profile',
          title: 'সদস্য প্রোফাইল',
          englishTitle: 'Member 360 View',
          icon: Icons.account_box_outlined,
          route: RouteNames.memberProfile,
          sortOrder: 3,
          description: 'সদস্যের পূর্ণাঙ্গ বিবরণ ও দলিলপত্র',
        ),
        NavigationItem(
          id: 'members_applications',
          title: 'সদস্য আবেদন',
          englishTitle: 'Membership Applications',
          icon: Icons.assignment_ind_outlined,
          route: RouteNames.memberApplications,
          sortOrder: 4,
          description: 'নতুন সদস্যপদ ও সংশোধনের আবেদন',
        ),
        NavigationItem(
          id: 'members_accounts',
          title: 'সদস্যের হিসাব',
          englishTitle: 'Member Ledgers',
          icon: Icons.account_balance_wallet_outlined,
          route: RouteNames.memberAccounts,
          sortOrder: 5,
          description: 'সদস্যের ব্যালেন্স ও সাধারণ সঞ্চয় খতিয়ান',
        ),
        NavigationItem(
          id: 'members_shares',
          title: 'সদস্যের শেয়ার',
          englishTitle: 'Member Shares',
          icon: Icons.pie_chart_outline,
          route: RouteNames.memberShares,
          sortOrder: 6,
          description: 'সদস্যের অনুকূলে বরাদ্দকৃত শেয়ার সংখ্যা ও মূল্য',
        ),
        NavigationItem(
          id: 'members_installments',
          title: 'সদস্যের কিস্তি',
          englishTitle: 'Member Installments',
          icon: Icons.receipt_long_outlined,
          route: RouteNames.memberInstallments,
          sortOrder: 7,
          description: 'কিস্তি শিডিউল ও আদায় স্থিতি',
        ),
        NavigationItem(
          id: 'members_activities',
          title: 'সদস্যের কার্যক্রম',
          englishTitle: 'Activity Logs',
          icon: Icons.timeline_outlined,
          route: RouteNames.memberActivities,
          sortOrder: 8,
          description: 'সদস্যের উপস্থিতি ও অংশগ্রহণের ইতিহাস',
        ),
        NavigationItem(
          id: 'members_reports',
          title: 'রিপোর্ট',
          englishTitle: 'Member Reports',
          icon: Icons.summarize_outlined,
          route: RouteNames.memberReports,
          sortOrder: 9,
          description: 'সদস্য সম্পর্কিত অ্যানালিটিক্স ও রিপোর্ট',
        ),
      ],
    ),

    // ৪. মাস্টার ডাটা ও খাত ব্যবস্থাপনা
    NavigationItem(
      id: 'master_data',
      title: 'মাস্টার ডাটা ও খাত ব্যবস্থাপনা',
      englishTitle: 'Master Data Setup',
      icon: Icons.tune_outlined,
      route: RouteNames.masterData,
      sortOrder: 4,
      description: 'আয়-ব্যয় খাত, তহবিল ও সাধারণ কনফিগারেশন',
      children: [
        NavigationItem(
          id: 'master_income_heads',
          title: 'আয় খাত',
          englishTitle: 'Income Heads',
          icon: Icons.input_outlined,
          route: RouteNames.masterIncomeHeads,
          sortOrder: 1,
          description: 'আয়ের মৌলিক খাতসমূহ (ভর্তি ফি, মাসিক ফি ইত্যাদি)',
        ),
        NavigationItem(
          id: 'master_expense_heads',
          title: 'ব্যয় খাত',
          englishTitle: 'Expense Heads',
          icon: Icons.output_outlined,
          route: RouteNames.masterExpenseHeads,
          sortOrder: 2,
          description: 'ব্যয়ের খাতসমূহ (অফিস ভাড়া, আপ্যায়ন, স্টেশনারি)',
        ),
        NavigationItem(
          id: 'master_funds',
          title: 'তহবিল',
          englishTitle: 'Fund Master',
          icon: Icons.savings_outlined,
          route: RouteNames.masterFunds,
          sortOrder: 3,
          description: 'প্রশাসনিক, সাধারণ, শেয়ার, প্রকল্প ও কাস্টম তহবিল কনফিগ',
        ),
        NavigationItem(
          id: 'master_accounts',
          title: 'হিসাব',
          englishTitle: 'Account Master',
          icon: Icons.account_balance_outlined,
          route: RouteNames.masterAccounts,
          sortOrder: 4,
          description: 'ক্যাশ, ব্যাংক হিসাব ও মোবাইল ওয়ালেট তালিকা',
        ),
        NavigationItem(
          id: 'master_member_types',
          title: 'সদস্যের ধরন',
          englishTitle: 'Member Types',
          icon: Icons.category_outlined,
          route: RouteNames.masterMemberTypes,
          sortOrder: 5,
          description: 'স্থায়ী, সহযোগী ও আজীবন সদস্যের ক্যাটাগরি',
        ),
        NavigationItem(
          id: 'master_business_types',
          title: 'ব্যবসার ধরন',
          englishTitle: 'Business Categories',
          icon: Icons.storefront_outlined,
          route: RouteNames.masterBusinessTypes,
          sortOrder: 6,
          description: 'হালাল বিনিয়োগ ও বাণিজ্য ক্যাটাগরি',
        ),
        NavigationItem(
          id: 'master_products',
          title: 'পণ্য ও সেবা',
          englishTitle: 'Products & Services',
          icon: Icons.inventory_2_outlined,
          route: RouteNames.masterProducts,
          sortOrder: 7,
          description: 'ব্যবসা পণ্য ও সেবার মাস্টার তালিকা',
        ),
        NavigationItem(
          id: 'master_general_setup',
          title: 'সাধারণ সেটআপ',
          englishTitle: 'General Setup',
          icon: Icons.settings_applications_outlined,
          route: RouteNames.masterGeneralSetup,
          sortOrder: 8,
          description: 'কোড জেনারেশন, ফিসকাল বছর ও পলিসি সেটআপ',
        ),
        NavigationItem(
          id: 'master_reports',
          title: 'রিপোর্ট',
          englishTitle: 'Master Data Audit',
          icon: Icons.summarize_outlined,
          route: RouteNames.masterReports,
          sortOrder: 9,
          description: 'মাস্টার ডাটা অডিট ও তালিকা প্রিন্ট',
        ),
      ],
    ),

    // ৫. অর্থ ও হিসাব (3 Dimensions: Head, Fund, Account)
    NavigationItem(
      id: 'finance',
      title: 'অর্থ ও হিসাব',
      englishTitle: 'Finance & Accounting',
      icon: Icons.calculate_outlined,
      route: RouteNames.finance,
      sortOrder: 5,
      description: '৩-মাত্রিক ইসলামিক অ্যাকাউন্টিং (খাত, তহবিল ও হিসাব)',
      children: [
        NavigationItem(
          id: 'finance_income',
          title: 'আয়',
          englishTitle: 'Income Transactions',
          icon: Icons.add_circle_outline,
          route: RouteNames.financeIncome,
          sortOrder: 1,
          description: 'আয় ভাউচার ও রসিদ তৈরি',
        ),
        NavigationItem(
          id: 'finance_expense',
          title: 'ব্যয়',
          englishTitle: 'Expense Transactions',
          icon: Icons.remove_circle_outline,
          route: RouteNames.financeExpense,
          sortOrder: 2,
          description: 'ব্যয় ভাউচার ও অনুমোদন প্রক্রিয়া',
        ),
        NavigationItem(
          id: 'finance_transfer',
          title: 'স্থানান্তর',
          englishTitle: 'Fund Transfers',
          icon: Icons.swap_horiz_outlined,
          route: RouteNames.financeTransfer,
          sortOrder: 3,
          description: 'ক্যাশ-টু-ব্যাংক বা ফান্ড স্থানান্তর',
        ),
        NavigationItem(
          id: 'finance_funds',
          title: 'তহবিল',
          englishTitle: 'Fund Allocation',
          icon: Icons.layers_outlined,
          route: RouteNames.financeFunds,
          sortOrder: 4,
          description: 'তহবিলভিত্তিক ব্যালেন্স ও দায়বদ্ধতা বিশ্লেষণ',
        ),
        NavigationItem(
          id: 'finance_accounts',
          title: 'হিসাব',
          englishTitle: 'Accounts & Ledgers',
          icon: Icons.menu_book_outlined,
          route: RouteNames.financeAccounts,
          sortOrder: 5,
          description: 'হিসাবভিত্তিক জমা-খরচ রেজিস্টার',
        ),
        NavigationItem(
          id: 'finance_collectors',
          title: 'সংগ্রহকারী',
          englishTitle: 'Field Collectors',
          icon: Icons.hail_outlined,
          route: RouteNames.financeCollectors,
          sortOrder: 6,
          description: 'ফিল্ড কালেকশন শিট ও জমা হিসাব',
        ),
        NavigationItem(
          id: 'finance_cash',
          title: 'নগদ',
          englishTitle: 'Cash Register',
          icon: Icons.money_outlined,
          route: RouteNames.financeCash,
          sortOrder: 7,
          description: 'দৈনিক ক্যাশ বই ও ভল্ট ব্যালেন্স',
        ),
        NavigationItem(
          id: 'finance_bank',
          title: 'ব্যাংক',
          englishTitle: 'Bank Reconciliations',
          icon: Icons.account_balance_outlined,
          route: RouteNames.financeBank,
          sortOrder: 8,
          description: 'ব্যাংক স্টেটমেন্ট ও সমন্বয় বিবরণী',
        ),
        NavigationItem(
          id: 'finance_ledger',
          title: 'খতিয়ান',
          englishTitle: 'General Ledger',
          icon: Icons.auto_stories_outlined,
          route: RouteNames.financeLedger,
          sortOrder: 9,
          description: 'সাধারণ খতিয়ান ও ট্রায়াল ব্যালেন্স',
        ),
        NavigationItem(
          id: 'finance_budget',
          title: 'বাজেট',
          englishTitle: 'Budgeting',
          icon: Icons.trending_up_outlined,
          route: RouteNames.financeBudget,
          sortOrder: 10,
          description: 'বার্ষিক বাজেট বরাদ্দ ও বাস্তবায়ন চিত্র',
        ),
        NavigationItem(
          id: 'finance_reports',
          title: 'রিপোর্ট',
          englishTitle: 'Financial Statements',
          icon: Icons.assessment_outlined,
          route: RouteNames.financeReports,
          sortOrder: 11,
          description: 'আয়-ব্যয় বিবরণী, উদ্বৃত্তপত্র ও হিসাব নিরীক্ষা',
        ),
      ],
    ),

    // ৬. শেয়ার ও প্রকল্প
    NavigationItem(
      id: 'shares_projects',
      title: 'শেয়ার ও প্রকল্প',
      englishTitle: 'Shares & Projects',
      icon: Icons.pie_chart_outline,
      route: RouteNames.sharesProjects,
      sortOrder: 6,
      description: 'সমিতির মূলধন শেয়ার ও যৌথ মুদারাবা/মুশারাকা প্রকল্প',
      children: [
        NavigationItem(
          id: 'sp_projects',
          title: 'প্রকল্প',
          englishTitle: 'Project Directory',
          icon: Icons.workspaces_outline,
          route: RouteNames.projectList,
          sortOrder: 1,
          description: 'চলমান ও প্রস্তাবিত যৌথ প্রকল্পসমূহ',
        ),
        NavigationItem(
          id: 'sp_participation',
          title: 'প্রকল্প অংশগ্রহণ',
          englishTitle: 'Project Subscriptions',
          icon: Icons.group_add_outlined,
          route: RouteNames.projectParticipation,
          sortOrder: 2,
          description: 'প্রকল্পে সদস্যদের ইউনিট বিনিয়োগ ও অনুমোদন',
        ),
        NavigationItem(
          id: 'sp_shares',
          title: 'শেয়ার',
          englishTitle: 'Capital Shares',
          icon: Icons.token_outlined,
          route: RouteNames.shareList,
          sortOrder: 3,
          description: 'সমিতির মূলধন শেয়ার খতিয়ান',
        ),
        NavigationItem(
          id: 'sp_allocation',
          title: 'শেয়ার বরাদ্দ',
          englishTitle: 'Share Allocation',
          icon: Icons.how_to_reg_outlined,
          route: RouteNames.shareAllocation,
          sortOrder: 4,
          description: 'নতুন শেয়ার আবেদন ও বরাদ্দ অনুমোদন',
        ),
        NavigationItem(
          id: 'sp_installments',
          title: 'শেয়ার কিস্তি',
          englishTitle: 'Share Installments',
          icon: Icons.calendar_month_outlined,
          route: RouteNames.shareInstallments,
          sortOrder: 5,
          description: 'শেয়ার ক্রয়ের নির্ধারিত কিস্তির শিডিউল',
        ),
        NavigationItem(
          id: 'sp_payments',
          title: 'পেমেন্ট',
          englishTitle: 'Share Payments',
          icon: Icons.payments_outlined,
          route: RouteNames.sharePayments,
          sortOrder: 6,
          description: 'শেয়ার মূল্য পরিশোধ ও রসিদ',
        ),
        NavigationItem(
          id: 'sp_certificates',
          title: 'শেয়ার সার্টিফিকেট',
          englishTitle: 'Certificates',
          icon: Icons.card_membership_outlined,
          route: RouteNames.shareCertificates,
          sortOrder: 7,
          description: 'ডিজিটাল শেয়ার সনদ প্রস্তুত ও প্রিন্ট',
        ),
        NavigationItem(
          id: 'sp_completion',
          title: 'প্রকল্প সমাপ্তি',
          englishTitle: 'Project Closure',
          icon: Icons.task_alt_outlined,
          route: RouteNames.projectCompletion,
          sortOrder: 8,
          description: 'প্রকল্প সমাপনী হিসাব ও লভ্যাংশ বণ্টন',
        ),
        NavigationItem(
          id: 'sp_reports',
          title: 'রিপোর্ট',
          englishTitle: 'Share Reports',
          icon: Icons.analytics_outlined,
          route: RouteNames.shareReports,
          sortOrder: 9,
          description: 'শেয়ার হোল্ডিং ও প্রকল্প পারফরম্যান্স রিপোর্ট',
        ),
      ],
    ),

    // ৭. হালাল ব্যবসা
    NavigationItem(
      id: 'halal_business',
      title: 'হালাল ব্যবসা',
      englishTitle: 'Halal Trade & Sales',
      icon: Icons.storefront_outlined,
      route: RouteNames.halalBusiness,
      sortOrder: 7,
      description: 'মুরাবাহা ক্রয়-বিক্রয়, ইনভেন্টরি ও হালাল বাণিজ্য',
      children: [
        NavigationItem(
          id: 'hb_dashboard',
          title: 'ব্যবসার ড্যাশবোর্ড',
          englishTitle: 'Trade Dashboard',
          icon: Icons.insights_outlined,
          route: RouteNames.businessDashboard,
          sortOrder: 1,
          description: 'দৈনিক বিক্রয়, মজুদ ও আদায়ের সারসংক্ষেপ',
        ),
        NavigationItem(
          id: 'hb_suppliers',
          title: 'সরবরাহকারী',
          englishTitle: 'Suppliers',
          icon: Icons.local_shipping_outlined,
          route: RouteNames.businessSuppliers,
          sortOrder: 2,
          description: 'পাইকারি সরবরাহকারী প্রতিষ্ঠান ও হিসাব',
        ),
        NavigationItem(
          id: 'hb_purchase',
          title: 'ক্রয়',
          englishTitle: 'Purchases (Murabaha In)',
          icon: Icons.shopping_bag_outlined,
          route: RouteNames.businessPurchase,
          sortOrder: 3,
          description: 'পণ্য ক্রয় ভাউচার ও চালানের এন্ট্রি',
        ),
        NavigationItem(
          id: 'hb_products',
          title: 'পণ্য ও সেবা',
          englishTitle: 'Product Catalog',
          icon: Icons.category_outlined,
          route: RouteNames.businessProducts,
          sortOrder: 4,
          description: 'ট্রেডিং পণ্যের তালিকা ও মূল্য নির্ধারণ',
        ),
        NavigationItem(
          id: 'hb_inventory',
          title: 'মজুদ',
          englishTitle: 'Stock & Inventory',
          icon: Icons.warehouse_outlined,
          route: RouteNames.businessInventory,
          sortOrder: 5,
          description: 'গুদাম মজুদ ও স্টক ব্যালেন্স ট্র্যাকিং',
        ),
        NavigationItem(
          id: 'hb_sales',
          title: 'বিক্রয়',
          englishTitle: 'Sales Register',
          icon: Icons.point_of_sale_outlined,
          route: RouteNames.businessSales,
          sortOrder: 6,
          description: 'নগদ ও পাইকারি বিক্রয় রসিদ',
        ),
        NavigationItem(
          id: 'hb_customers',
          title: 'গ্রাহক',
          englishTitle: 'Customers / Clients',
          icon: Icons.person_search_outlined,
          route: RouteNames.businessCustomers,
          sortOrder: 7,
          description: 'ক্রেতা প্রোফাইল ও লেনদেন ইতিহাস',
        ),
        NavigationItem(
          id: 'hb_installment_sales',
          title: 'কিস্তি বিক্রয়',
          englishTitle: 'Installment Sales (Fixed Profit)',
          icon: Icons.calendar_today_outlined,
          route: RouteNames.businessInstallmentSales,
          sortOrder: 8,
          description: 'নির্ধারিত মুনাফায় কিস্তি বিক্রয় শিডিউল (সুদমুক্ত)',
        ),
        NavigationItem(
          id: 'hb_contracts',
          title: 'বিক্রয় চুক্তি',
          englishTitle: 'Sales Contracts',
          icon: Icons.gavel_outlined,
          route: RouteNames.businessContracts,
          sortOrder: 9,
          description: 'মুরাবাহা বিক্রয় চুক্তি ও জামিনদার বিবরণ',
        ),
        NavigationItem(
          id: 'hb_collections',
          title: 'আদায়',
          englishTitle: 'Installment Collections',
          icon: Icons.price_check_outlined,
          route: RouteNames.businessCollections,
          sortOrder: 10,
          description: 'বকেয়া ও কিস্তির টাকা আদায় এন্ট্রি',
        ),
        NavigationItem(
          id: 'hb_dues',
          title: 'বকেয়া',
          englishTitle: 'Due Trackers',
          icon: Icons.pending_outlined,
          route: RouteNames.businessDues,
          sortOrder: 11,
          description: 'গ্রাহকভিত্তিক বকেয়া তালিকা ও তাগাদা নোটিশ',
        ),
        NavigationItem(
          id: 'hb_reports',
          title: 'রিপোর্ট',
          englishTitle: 'Trade Reports',
          icon: Icons.query_stats_outlined,
          route: RouteNames.businessReports,
          sortOrder: 12,
          description: 'লাভ-ক্ষতি ও ইনভেন্টরি ঘূর্ণন রিপোর্ট',
        ),
      ],
    ),

    // ৮. জমি, সম্পত্তি ও সম্পদ
    NavigationItem(
      id: 'assets',
      title: 'জমি, সম্পত্তি ও সম্পদ',
      englishTitle: 'Property & Fixed Assets',
      icon: Icons.domain_outlined,
      route: RouteNames.assets,
      sortOrder: 8,
      description: 'সমিতির জমি, ভবন, গাড়ি ও স্থায়ী সম্পদের রেজিস্টার',
      children: [
        NavigationItem(
          id: 'asset_land',
          title: 'জমি',
          englishTitle: 'Land Properties',
          icon: Icons.landscape_outlined,
          route: RouteNames.assetLand,
          sortOrder: 1,
          description: 'জমির খতিয়ান, দাগ নম্বর ও দলিল তথ্য',
        ),
        NavigationItem(
          id: 'asset_buildings',
          title: 'ভবন',
          englishTitle: 'Buildings & Offices',
          icon: Icons.apartment_outlined,
          route: RouteNames.assetBuildings,
          sortOrder: 2,
          description: 'সমিতির মালিকানাধীন ভবন ও স্থাপনা',
        ),
        NavigationItem(
          id: 'asset_vehicles',
          title: 'যানবাহন',
          englishTitle: 'Vehicles',
          icon: Icons.directions_car_outlined,
          route: RouteNames.assetVehicles,
          sortOrder: 3,
          description: 'মোটরযান ও পরিবহন সম্পদ রেজিস্টার',
        ),
        NavigationItem(
          id: 'asset_equipment',
          title: 'যন্ত্রপাতি',
          englishTitle: 'Machinery & Equipment',
          icon: Icons.precision_manufacturing_outlined,
          route: RouteNames.assetEquipment,
          sortOrder: 4,
          description: 'আইটি সামগ্রী, জেনারেটর ও অফিস ইকুইপমেন্ট',
        ),
        NavigationItem(
          id: 'asset_furniture',
          title: 'আসবাবপত্র',
          englishTitle: 'Furniture & Fixtures',
          icon: Icons.chair_outlined,
          route: RouteNames.assetFurniture,
          sortOrder: 5,
          description: 'টেবিল, চেয়ার ও অন্যান্য অফিস ফার্নিচার',
        ),
        NavigationItem(
          id: 'asset_other',
          title: 'অন্যান্য সম্পদ',
          englishTitle: 'Other Fixed Assets',
          icon: Icons.devices_other_outlined,
          route: RouteNames.assetOther,
          sortOrder: 6,
          description: 'বিবিধ স্থায়ী ও দীর্ঘমেয়াদী সম্পত্তি',
        ),
        NavigationItem(
          id: 'asset_transfer',
          title: 'সম্পদ হস্তান্তর',
          englishTitle: 'Asset Disposal / Transfers',
          icon: Icons.move_up_outlined,
          route: RouteNames.assetTransfer,
          sortOrder: 7,
          description: 'সম্পদ বিক্রয়, হস্তান্তর বা অবচয় রেকর্ড',
        ),
        NavigationItem(
          id: 'asset_maintenance',
          title: 'সম্পদ রক্ষণাবেক্ষণ',
          englishTitle: 'Maintenance & Repairs',
          icon: Icons.build_outlined,
          route: RouteNames.assetMaintenance,
          sortOrder: 8,
          description: 'সার্ভিসিং ও মেরামত সংক্রান্ত খরচের লগ',
        ),
        NavigationItem(
          id: 'asset_reports',
          title: 'রিপোর্ট',
          englishTitle: 'Asset Valuation Report',
          icon: Icons.table_view_outlined,
          route: RouteNames.assetReports,
          sortOrder: 9,
          description: 'সম্পদ মূল্যায়ন ও বুক ভ্যালু বিবরণী',
        ),
      ],
    ),

    // ৯. কমিটি, সভা ও পরিচালনা
    NavigationItem(
      id: 'governance',
      title: 'কমিটি, সভা ও পরিচালনা',
      englishTitle: 'Governance & Meetings',
      icon: Icons.diversity_3_outlined,
      route: RouteNames.governance,
      sortOrder: 9,
      description: 'ব্যবস্থাপনা কমিটি, সাধারণ সভা ও রেজুলেশন বুক',
      children: [
        NavigationItem(
          id: 'gov_committees',
          title: 'কমিটি',
          englishTitle: 'Committee Roster',
          icon: Icons.groups_2_outlined,
          route: RouteNames.governanceCommittees,
          sortOrder: 1,
          description: 'কার্যনির্বাহী ও সাব-কমিটি তালিকা',
        ),
        NavigationItem(
          id: 'gov_roles',
          title: 'পদ ও দায়িত্ব',
          englishTitle: 'Designations & Duties',
          icon: Icons.work_outline,
          route: RouteNames.governanceRoles,
          sortOrder: 2,
          description: 'সভাপতি, সম্পাদক ও সদস্যদের কার্যপরিধি',
        ),
        NavigationItem(
          id: 'gov_members',
          title: 'কমিটি সদস্য',
          englishTitle: 'Committee Members',
          icon: Icons.person_pin_outlined,
          route: RouteNames.governanceMembers,
          sortOrder: 3,
          description: 'বর্তমান কমিটির মেম্বার প্রোফাইল',
        ),
        NavigationItem(
          id: 'gov_tenure',
          title: 'কমিটির মেয়াদ',
          englishTitle: 'Committee Terms',
          icon: Icons.date_range_outlined,
          route: RouteNames.governanceTenure,
          sortOrder: 4,
          description: 'কমিটির মেয়াদকাল ও নির্বাচনের তারিখ',
        ),
        NavigationItem(
          id: 'gov_meetings',
          title: 'সভা',
          englishTitle: 'Meeting Schedules',
          icon: Icons.event_outlined,
          route: RouteNames.governanceMeetings,
          sortOrder: 5,
          description: 'মাসিক সভা ও বার্ষিক সাধারণ সভা (AGM)',
        ),
        NavigationItem(
          id: 'gov_attendance',
          title: 'উপস্থিতি',
          englishTitle: 'Attendance Register',
          icon: Icons.co_present_outlined,
          route: RouteNames.governanceAttendance,
          sortOrder: 6,
          description: 'সভায় উপস্থিতির ডিজিটাল খাতা',
        ),
        NavigationItem(
          id: 'gov_agendas',
          title: 'এজেন্ডা',
          englishTitle: 'Meeting Agendas',
          icon: Icons.view_list_outlined,
          route: RouteNames.governanceAgendas,
          sortOrder: 7,
          description: 'সভার আলোচ্যসূচি নির্ধারণ ও প্রণয়ন',
        ),
        NavigationItem(
          id: 'gov_resolutions',
          title: 'সিদ্ধান্ত / Resolution',
          englishTitle: 'Resolutions & Minutes',
          icon: Icons.fact_check_outlined,
          route: RouteNames.governanceResolutions,
          sortOrder: 8,
          description: 'সভার চূড়ান্ত সিদ্ধান্ত ও কার্যবিবরণী',
        ),
        NavigationItem(
          id: 'gov_notices',
          title: 'নোটিশ',
          englishTitle: 'Meeting Notices',
          icon: Icons.notifications_active_outlined,
          route: RouteNames.governanceNotices,
          sortOrder: 9,
          description: 'সভা ও বিশেষ অধিবেশনের বিজ্ঞপ্তি জারি',
        ),
        NavigationItem(
          id: 'gov_attachments',
          title: 'সংযুক্তি',
          englishTitle: 'Meeting Attachments',
          icon: Icons.attachment_outlined,
          route: RouteNames.governanceAttachments,
          sortOrder: 10,
          description: 'স্বাক্ষরিত রেজুলেশন শিট ও প্রসিডিংস স্ক্যান',
        ),
        NavigationItem(
          id: 'gov_reports',
          title: 'রিপোর্ট',
          englishTitle: 'Governance Reports',
          icon: Icons.summarize_outlined,
          route: RouteNames.governanceReports,
          sortOrder: 11,
          description: 'কার্যবিবরণী আর্কাইভ ও পরিচালনা রিপোর্ট',
        ),
      ],
    ),

    // ১০. ডকুমেন্ট ও Google Drive
    NavigationItem(
      id: 'documents',
      title: 'ডকুমেন্ট ও Google Drive',
      englishTitle: 'Documents & Cloud Storage',
      icon: Icons.folder_shared_outlined,
      route: RouteNames.documents,
      sortOrder: 10,
      description: 'অফিসিয়াল ফাইল সংরক্ষণ ও গুগল ড্রাইভ ব্যাকআপ',
      children: [
        NavigationItem(
          id: 'doc_all',
          title: 'সকল ডকুমেন্ট',
          englishTitle: 'All Documents',
          icon: Icons.folder_open_outlined,
          route: RouteNames.docAll,
          sortOrder: 1,
          description: 'সংগঠনের সকল সংরক্ষিত ডকুমেন্টের তালিকা',
        ),
        NavigationItem(
          id: 'doc_local_upload',
          title: 'স্থানীয় আপলোড',
          englishTitle: 'Local Uploads',
          icon: Icons.upload_file_outlined,
          route: RouteNames.docLocalUpload,
          sortOrder: 2,
          description: 'সার্ভারে সরাসরি স্ক্যান কপি ও পিডিএফ আপলোড',
        ),
        NavigationItem(
          id: 'doc_google_drive',
          title: 'Google Drive',
          englishTitle: 'Google Drive Link',
          icon: Icons.cloud_outlined,
          route: RouteNames.docGoogleDrive,
          sortOrder: 3,
          description: 'গুগল ড্রাইভ ক্লাউড ব্যাকআপ সিঙ্ক্রোনাইজেশন',
        ),
        NavigationItem(
          id: 'doc_types',
          title: 'ডকুমেন্টের ধরন',
          englishTitle: 'Document Categories',
          icon: Icons.folder_special_outlined,
          route: RouteNames.docTypes,
          sortOrder: 4,
          description: 'দলিল, চুক্তি, সনদ ও আবেদনপত্রের শ্রেণিবিভাগ',
        ),
        NavigationItem(
          id: 'doc_shared',
          title: 'শেয়ার্ড ডকুমেন্ট',
          englishTitle: 'Shared Files',
          icon: Icons.share_outlined,
          route: RouteNames.docShared,
          sortOrder: 5,
          description: 'কমিটি বা সদস্যদের সাথে শেয়ারকৃত ফাইল',
        ),
        NavigationItem(
          id: 'doc_search',
          title: 'ডকুমেন্ট অনুসন্ধান',
          englishTitle: 'Document Search',
          icon: Icons.search_outlined,
          route: RouteNames.docSearch,
          sortOrder: 6,
          description: 'ট্যাগ ও কি-ওয়ার্ডভিত্তিক দ্রুত ফাইল সার্চ',
        ),
        NavigationItem(
          id: 'doc_reports',
          title: 'রিপোর্ট',
          englishTitle: 'Document Audit Logs',
          icon: Icons.list_alt_outlined,
          route: RouteNames.docReports,
          sortOrder: 7,
          description: 'ফাইল এক্সেস ও ডাউনলোড হিস্টোরি লগ',
        ),
      ],
    ),

    // ১১. রিপোর্ট ও বিশ্লেষণ
    NavigationItem(
      id: 'reports',
      title: 'রিপোর্ট ও বিশ্লেষণ',
      englishTitle: 'Reports & Analytics',
      icon: Icons.bar_chart_outlined,
      route: RouteNames.reports,
      sortOrder: 11,
      description: 'কেন্দ্রীয় রিপোর্ট সেন্টার ও এক্সিকিউটিভ অ্যানালিটিক্স',
      children: [
        NavigationItem(
          id: 'rep_center',
          title: 'Report Center',
          englishTitle: 'Central Report Hub',
          icon: Icons.dashboard_customize_outlined,
          route: RouteNames.reportCenter,
          sortOrder: 1,
          description: 'এক ক্লিকে সকল মডিউলের রিপোর্ট হাব',
        ),
        NavigationItem(
          id: 'rep_financial',
          title: 'আর্থিক রিপোর্ট',
          englishTitle: 'Financial Statements',
          icon: Icons.account_balance_wallet_outlined,
          route: RouteNames.reportFinancial,
          sortOrder: 2,
          description: 'আয়-ব্যয়, ট্রায়াল ব্যালেন্স ও ক্যাশ ফ্লো',
        ),
        NavigationItem(
          id: 'rep_members',
          title: 'সদস্য রিপোর্ট',
          englishTitle: 'Member Summary',
          icon: Icons.people_alt_outlined,
          route: RouteNames.reportMembers,
          sortOrder: 3,
          description: 'সদস্য অন্তর্ভুক্তি ও সঞ্চয় বিবরণী',
        ),
        NavigationItem(
          id: 'rep_shares',
          title: 'শেয়ার রিপোর্ট',
          englishTitle: 'Share Register',
          icon: Icons.pie_chart_outline,
          route: RouteNames.reportShares,
          sortOrder: 4,
          description: 'শেয়ারহোল্ডার তালিকা ও সার্টিফিকেট রিপোর্ট',
        ),
        NavigationItem(
          id: 'rep_projects',
          title: 'প্রকল্প রিপোর্ট',
          englishTitle: 'Project Performance',
          icon: Icons.architecture_outlined,
          route: RouteNames.reportProjects,
          sortOrder: 5,
          description: 'প্রকল্প বিনিয়োগ ও অগ্রগতি চিত্র',
        ),
        NavigationItem(
          id: 'rep_business',
          title: 'ব্যবসা রিপোর্ট',
          englishTitle: 'Sales & Inventory Profit',
          icon: Icons.store_outlined,
          route: RouteNames.reportBusiness,
          sortOrder: 6,
          description: 'হালাল ট্রেডিং লাভ ও বকেয়া রিপোর্ট',
        ),
        NavigationItem(
          id: 'rep_assets',
          title: 'সম্পদ রিপোর্ট',
          englishTitle: 'Fixed Assets Schedule',
          icon: Icons.apartment_outlined,
          route: RouteNames.reportAssets,
          sortOrder: 7,
          description: 'স্থায়ী সম্পদ রেজিস্টার ও অবচয় চার্ট',
        ),
        NavigationItem(
          id: 'rep_governance',
          title: 'কমিটি রিপোর্ট',
          englishTitle: 'Meeting Attendances',
          icon: Icons.groups_outlined,
          route: RouteNames.reportGovernance,
          sortOrder: 8,
          description: 'সভা ও উপস্থিতি অ্যানালিটিক্স',
        ),
        NavigationItem(
          id: 'rep_documents',
          title: 'ডকুমেন্ট রিপোর্ট',
          englishTitle: 'Storage Metrics',
          icon: Icons.snippet_folder_outlined,
          route: RouteNames.reportDocuments,
          sortOrder: 9,
          description: 'ক্লাউড স্টোরেজ ও ফাইল মেকানিক্স',
        ),
        NavigationItem(
          id: 'rep_custom',
          title: 'Custom Report',
          englishTitle: 'Custom Report Builder',
          icon: Icons.tune_outlined,
          route: RouteNames.reportCustom,
          sortOrder: 10,
          description: 'ফিল্টার ও শর্তভিত্তিক কাস্টম রিপোর্ট তৈরি',
        ),
      ],
    ),

    // ১২. প্রশাসন ও সেটিংস
    NavigationItem(
      id: 'administration',
      title: 'প্রশাসন ও সেটিংস',
      englishTitle: 'Administration & System',
      icon: Icons.settings_suggest_outlined,
      route: RouteNames.administration,
      sortOrder: 12,
      description: 'সিস্টেম কনফিগারেশন, অডিট ট্রেইল ও ব্যাকআপ',
      children: [
        NavigationItem(
          id: 'adm_app_settings',
          title: 'অ্যাপ সেটিংস',
          englishTitle: 'App Preferences',
          icon: Icons.display_settings_outlined,
          route: RouteNames.adminAppSettings,
          sortOrder: 1,
          description: 'থিম, ভাষা, মুদ্রা ও ডিসপ্লে কনফিগারেশন',
        ),
        NavigationItem(
          id: 'adm_org_settings',
          title: 'সংগঠন সেটিংস',
          englishTitle: 'Tenant Configuration',
          icon: Icons.corporate_fare_outlined,
          route: RouteNames.adminOrgSettings,
          sortOrder: 2,
          description: 'সমিতির পলিসি ও কার্যপ্রণালী নির্ধারণ',
        ),
        NavigationItem(
          id: 'adm_user_settings',
          title: 'ব্যবহারকারী সেটিংস',
          englishTitle: 'User Security Matrix',
          icon: Icons.manage_accounts_outlined,
          route: RouteNames.adminUserSettings,
          sortOrder: 3,
          description: 'ইউজার প্রোফাইল ও পাসওয়ার্ড পলিসি',
        ),
        NavigationItem(
          id: 'adm_permissions',
          title: 'অনুমতি',
          englishTitle: 'Permission Engine',
          icon: Icons.lock_person_outlined,
          route: RouteNames.adminPermissions,
          sortOrder: 4,
          description: 'মেনু ও অ্যাকশনভিত্তিক অনুমতি নির্ধারণ',
        ),
        NavigationItem(
          id: 'adm_notifications',
          title: 'নোটিফিকেশন',
          englishTitle: 'SMS & Email Alerts',
          icon: Icons.notifications_none_outlined,
          route: RouteNames.adminNotifications,
          sortOrder: 5,
          description: 'এসএমএস গেটওয়ে ও নোটিফিকেশন কনফিগ',
        ),
        NavigationItem(
          id: 'adm_backup',
          title: 'ডাটা ও ব্যাকআপ',
          englishTitle: 'Database Backups',
          icon: Icons.backup_outlined,
          route: RouteNames.adminBackup,
          sortOrder: 6,
          description: 'ডাটাবেজ ব্যাকআপ ডাউনলোড ও এক্সপোর্ট',
        ),
        NavigationItem(
          id: 'adm_integrations',
          title: 'ইন্টিগ্রেশন',
          englishTitle: 'External APIs',
          icon: Icons.integration_instructions_outlined,
          route: RouteNames.adminIntegrations,
          sortOrder: 7,
          description: 'ড্রাইভ, পেমেন্ট গেটওয়ে ও ক্লাউড সংযোগ',
        ),
        NavigationItem(
          id: 'adm_audit',
          title: 'অডিট',
          englishTitle: 'System Audit Logs',
          icon: Icons.fact_check_outlined,
          route: RouteNames.adminAudit,
          sortOrder: 8,
          description: 'সিস্টেমব্যাপী প্রতিটি ক্রিয়াকলাপের অডিট লগ',
        ),
        NavigationItem(
          id: 'adm_system_info',
          title: 'সিস্টেম তথ্য',
          englishTitle: 'System Environment',
          icon: Icons.info_outline,
          route: RouteNames.adminSystemInfo,
          sortOrder: 9,
          description: 'ভার্সন, সার্ভার স্ট্যাটাস ও আর্কিটেকচার তথ্য',
        ),
      ],
    ),

    // ১৩. সহায়িকা
    NavigationItem(
      id: 'help_guide',
      title: 'সহায়িকা',
      englishTitle: 'Help & Knowledge Base',
      icon: Icons.help_outline,
      route: RouteNames.helpGuide,
      sortOrder: 13,
      description: 'ব্যবহারকারী নির্দেশিকা, শরিয়াহ মূলনীতি ও সহায়তা',
      children: [
        NavigationItem(
          id: 'help_getting_started',
          title: 'শুরু করার নির্দেশিকা',
          englishTitle: 'Quickstart Guide',
          icon: Icons.rocket_launch_outlined,
          route: RouteNames.helpGettingStarted,
          sortOrder: 1,
          description: 'সফটওয়্যার ব্যবহারের প্রাথমিক ধাপসমূহ',
        ),
        NavigationItem(
          id: 'help_user_manual',
          title: 'ব্যবহার নির্দেশিকা',
          englishTitle: 'User Manual',
          icon: Icons.menu_book_outlined,
          route: RouteNames.helpUserManual,
          sortOrder: 2,
          description: 'প্রতিটি ফিচারের বিস্তারিত ব্যবহার পদ্ধতি',
        ),
        NavigationItem(
          id: 'help_faq',
          title: 'FAQ',
          englishTitle: 'Frequently Asked Questions',
          icon: Icons.quiz_outlined,
          route: RouteNames.helpFaq,
          sortOrder: 3,
          description: 'সাধারণ জিজ্ঞাসাসমূহ ও সমাধান',
        ),
        NavigationItem(
          id: 'help_accounting',
          title: 'হিসাব ব্যবস্থাপনা নির্দেশিকা',
          englishTitle: 'Accounting Concepts Guide',
          icon: Icons.account_balance_outlined,
          route: RouteNames.helpAccounting,
          sortOrder: 4,
          description: 'খাত, তহবিল ও হিসাবের সঠিক ব্যবহার নির্দেশিকা',
        ),
        NavigationItem(
          id: 'help_halal_business',
          title: 'হালাল ব্যবসা নির্দেশিকা',
          englishTitle: 'Halal Business Principles',
          icon: Icons.storefront_outlined,
          route: RouteNames.helpHalalBusiness,
          sortOrder: 5,
          description: 'মুরাবাহা ও কিস্তি বিক্রয়ের সুদমুক্ত নিয়মনীতি',
        ),
        NavigationItem(
          id: 'help_shariah_principles',
          title: 'শরিয়াহ নীতিমালা',
          englishTitle: 'Shariah Governance Standards',
          icon: Icons.gavel_outlined,
          route: RouteNames.helpShariahPrinciples,
          sortOrder: 6,
          description: 'তথ্যবহুল শরিয়াহ নির্দেশিকা (এটি ফতোয়া প্রদানকারী নয়)',
        ),
        NavigationItem(
          id: 'help_support',
          title: 'যোগাযোগ / Support',
          englishTitle: 'Technical Support',
          icon: Icons.contact_support_outlined,
          route: RouteNames.helpSupport,
          sortOrder: 7,
          description: 'টেকনিক্যাল সাপোর্ট ও হেল্পডেস্ক যোগাযোগ',
        ),
        NavigationItem(
          id: 'help_about',
          title: 'About',
          englishTitle: 'About Tijarah Society Software',
          icon: Icons.info_outline,
          route: RouteNames.helpAbout,
          sortOrder: 8,
          description: 'সফটওয়্যার পরিচিতি ও ডেডিকেটেড টিম',
        ),
      ],
    ),
  ];

  /// রুট স্ট্রিং দিয়ে মেইন প্যারেন্ট মডিউল খুঁজে বের করা
  static NavigationItem? findParentModuleByRoute(String route) {
    for (final module in mainModules) {
      if (module.route == route) return module;
      for (final child in module.children) {
        if (child.route == route) return module;
      }
    }
    return null;
  }

  /// রুট স্ট্রিং দিয়ে নির্দিষ্ট নেভিগেশন আইটেম (প্যারেন্ট বা চাইল্ড) খুঁজে বের করা
  static NavigationItem? findItemByRoute(String route) {
    for (final module in mainModules) {
      if (module.route == route) return module;
      for (final child in module.children) {
        if (child.route == route) return child;
      }
    }
    return null;
  }

  /// ব্রেডক্রাম্ব পাথ তৈরি করা
  static List<BreadcrumbItem> getBreadcrumbs(String route) {
    if (route == RouteNames.dashboard || route == RouteNames.initial || route == RouteNames.shell) {
      return [
        const BreadcrumbItem(title: 'ড্যাশবোর্ড', route: RouteNames.dashboard, isCurrent: true),
      ];
    }

    final parent = findParentModuleByRoute(route);
    if (parent == null) {
      return [
        const BreadcrumbItem(title: 'ড্যাশবোর্ড', route: RouteNames.dashboard),
        BreadcrumbItem(title: route, route: route, isCurrent: true),
      ];
    }

    if (parent.route == route) {
      return [
        const BreadcrumbItem(title: 'ড্যাশবোর্ড', route: RouteNames.dashboard),
        BreadcrumbItem(title: parent.title, route: parent.route, isCurrent: true),
      ];
    }

    final child = parent.children.firstWhere(
      (c) => c.route == route,
      orElse: () => NavigationItem(
        id: 'unknown',
        title: route,
        icon: Icons.chevron_right,
        route: route,
        sortOrder: 99,
      ),
    );

    return [
      const BreadcrumbItem(title: 'ড্যাশবোর্ড', route: RouteNames.dashboard),
      BreadcrumbItem(title: parent.title, route: parent.route),
      BreadcrumbItem(title: child.title, route: child.route, isCurrent: true),
    ];
  }
}
